name: Java CI

on:
  push:
    branches:
      - 'master'
      - 'test-demo'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '11'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Test with Gradle
      run: ./gradlew clean test

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      run: ./gradlew build --info

    - name: Deploy the backend for sample app
      if: github.ref == 'refs/heads/test-demo' && github.event_name == 'push'
      uses: azure/webapps-deploy@v2
      with:
        app-name: test-backend-springboot-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST }}
        package: 'build/libs/*.jar'
